services:
  picpaysimplificado:
    image: valentedev/picpaysimplificado:0.0.1-SNAPSHOT
    container_name: application
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - rabbitmq
  postgresql:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_valente:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_valente:/var/lib/rabbitmq
volumes:
  db_valente:
  rabbitmq_valente: