services:
  postgresql:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
      POSTGRES_USER: ${ENV_POSTGRES_USER}
      POSTGRES_DB: ${ENV_POSTGRES_DB}
      PGTZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - db_valente:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 3032
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_valente:/var/lib/rabbitmq
volumes:
  db_valente:
  rabbitmq_valente: