spring:
  application:
    name: picpaysimplificado
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/picpaysimplificado?createDatabaseIfNotExist=true
    password: ${DATA_BASE_PASSWORD:3222}
    username: ${DATA_BASE_USERNAME:postgres}
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 3032
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 5
          max-interval: 10000ms
        concurrency: 3
        max-concurrency: 10

logging:
  level:
    net.ttddyy.dsproxy.listener: debug
server:
  error:
    include-stacktrace: never

web:
  authorization-uri: /v2/authorize
  notify-uri: /v1/notify
  url: https://util.devi.tools/api

