TRUNCATE TABLE tbl_wallet RESTART IDENTITY CASCADE;
TRUNCATE TABLE tbl_shopkeeper RESTART IDENTITY CASCADE;
TRUNCATE TABLE tbl_common RESTART IDENTITY CASCADE;
TRUNCATE TABLE tbl_transaction RESTART IDENTITY CASCADE;

